name: Moj Prvi Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  pozdrav:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout koda
        uses: actions/checkout@v4
      - name: Ispisi pozdrav
        run: echo "Zdravo iz GitHub Actions!"
      - name: Pokazi datum i vrijeme
        run: date
      - name: Pokazi strukturu fajlova
        run: ls -la
