name: Bez Kesa

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Instaliraj zavisnosti (bez kesa)
        run: npm ci
      - name: Pokreni testove
        run: npm test
